### ISSUE TITLE
smartEasingThreshold is undefined

### ISSUE THREAD

**Issue by dib258** [jizai1125/vue-countup-v3#2]
Hello,

I encounter this error when I use the new package for Vue3.

```
vue-countup-v3.es.js:71 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'smartEasingThreshold')
    at t.determineDirectionAndSmartEasing (vue-countup-v3.es.js:71:36)
    at t.start (vue-countup-v3.es.js:79:66)
    at startAnim (vue-countup-v3.es.js:135:50)
    at loopAnim (vue-countup-v3.es.js:147:7)
    at vue-countup-v3.es.js:168:9
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2687:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:358:32)
    at render2 (runtime-core.esm-bundler.js:6211:9)
```

I use it like this 
```
<script setup>
    import CountUp from 'vue-countup-v3';
    import {ref} from 'vue';

    const options = ref({
        useEasing: true,
        useGrouping: true,
        separator: ' ',
        decimal: ',',
        prefix: '',
        suffix: ''
    });

    const optionsWithSuffix = (suffix) => {
        options.value.suffix = `${suffix}`;
        return options;
    }
</script>

<template>
    <CountUp
        :end-val="150"
        :options="options"
    />
</template>
```

Is there something wrong with the configuration or is it internal ?

Thanks in advance

**Comment by jizai1125** [comment]
@dib258 can you provide a reappearance link ? i try your code and didn't encounter this error.
link: https://codesandbox.io/s/vue-countup-v3-zh1ssl?file=/index.html

**Comment by dib258** [comment]
It seems to appear when using a suffix 

```
<template>
    <CountUp
        :end-val="150"
        :options="optionsWithSuffix(' / 5')"
    />
</template>
```

I don't know if the modification I made in your codesandbox.io is saved but here : https://codesandbox.io/s/dank-glitter-7udh4x?file=/src/Demo.vue

**Comment by jizai1125** [comment]
![image](https://user-images.githubusercontent.com/33979706/182053220-bb17c74c-7aed-473f-8af2-56e57be8d71e.png)
you should return `options.value` in function `optionsWithSuffix`, because `options` is a reactive variable.

**Comment by dib258** [comment]
What a silly mistake, sorry for the trouble and thank you! ;)

**Comment by jizai1125** [comment]
LOL, that's all right.
