### ISSUE TITLE
cannot read properties of undefined (reading 'defineComponent')

### ISSUE THREAD

**Issue by udisun** [jizai1125/vue-countup-v3#20]
**Describe the bug**
Getting errors on nuxt dev log running this module using `nitro`

**To Reproduce**
1. Install latest Nuxt
2. Install latest vue-countup-v3
3. create a new component:
```
<template>
  <ICountUp
    :end-val="number"
    :options="options"
  />
</template>
<script lang="ts" setup>
// @ts-ignore
import ICountUp from 'vue-countup-v3'

const props = withDefaults(defineProps<{
  number?: number,
  prefix?: string,
  decimal?: boolean
}>(), {
  number: 0,
  prefix: '$',
  decimal: true,
})

const options = computed(() => {
  return {
    useEasing: false,
    useGrouping: true,
    ...(props.decimal) && { decimalPlaces: 2 },
    separator: ',',
    ...(props.decimal) && { decimal: '.' },
    prefix: props.prefix,
    suffix: '',
    duration: 0.3,
  }
})

</script>

```
* remember that Nuxt by default load all components automatically

4. See error:
```
Nuxt Page Error:  Cannot read properties of undefined (reading 'defineComponent')

  <span class="stack internal">at ./node_modules/vue-countup-v3/dist/vue-countup-v3.umd.js:1:223</span>
  <span class="stack internal">at ./node_modules/vue-countup-v3/dist/vue-countup-v3.umd.js:1:232</span>
  <span class="stack internal">at ModuleJob.run (node:internal/modules/esm/module_job:218:25)</span>
  <span class="stack internal">at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)</span>
  <span class="stack internal">at async ViteNodeRunner.interopedImport (./node_modules/vite-node/dist/client.mjs:383:28)</span>
  <span class="stack internal">at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:253:24)</span>
  <span class="stack">at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:189:14)</span>
  <span class="stack internal">at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:233:12)</span>
  <span class="stack">at async ./components/common/CountUp.vue:3:31</span></pre>
[nuxt-app] app:error:cleared: 0.874ms
[nuxt-app] page:loading:start: 0.017ms
[nuxt-app] page:loading:end: 0.009ms
[nitro-runtime] error: 0.022ms
[nuxt-app] app:rendered: 0.251ms
```

**Expected behavior**
No errors should appear related to `vue-countup-v3`

**Screenshots**
![image](https://github.com/jizai1125/vue-countup-v3/assets/950100/c2fc63b5-1969-4a1e-96e1-79d8b9416640)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version latest

**Comment by jizai1125** [comment]
Try configguring `nuxt.config.ts` as follows:
```js
// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt3';

export default defineNuxtConfig({
  build: {
    transpile: ['vue-countup-v3'],
  },
});
```
Or wrapped by `<ClientOnly>` component

```vue
    <ClientOnly>
      <CountUp :end-val="3000" :options="{ enableScrollSpy: true }" />
    </ClientOnly>
```

**Comment by udisun** [comment]
> Try configguring `nuxt.config.ts` as follows:
> 
> ```js
> // nuxt.config.ts
> import { defineNuxtConfig } from 'nuxt3';
> 
> export default defineNuxtConfig({
>   build: {
>     transpile: ['vue-countup-v3'],
>   },
> });
> ```
> 
> Or wrapped by `<ClientOnly>` component
> 
> ```
>     <ClientOnly>
>       <CountUp :end-val="3000" :options="{ enableScrollSpy: true }" />
>     </ClientOnly>
> ```

Wrapping with `<client-only>` removes the error message.
Please add this to the README.md file and thank you for your help.
